---
# tasks file for task4
- name: install vsftpd
  yum: 
    name: vsftpd
    update_cache: true
    state: "{{ vsftpd_package }}"
  become: true

- include_tasks: linux.yml

- name: copy vsftpd.conf
  template:
    src: templates/vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    mode: 0600
  become: true
  notify: restart vsftpd

- name: "create {{ anon_root }} dir"
  file:
    path: "{{ anon_root }}"
    owner: ftp
    group: ftp
    mode: 0755
    state: directory
  become: true

- name: "create {{ anon_upload_root }} dir"
  file: 
    path: "{{ anon_upload_root }}"
    owner: ftp
    group: ftp
    mode: 0755
    setype: public_content_rw_t
    state: directory
  become: true

- name: vsftpd enabled
  service:
    name: vsftpd
    state: "{{ vsftpd_state }}"
    enabled: "{{ vsftpd_enabled }}"
  become: true

- name: firewalld
  yum:
    name: firewalld
    update_cache: true
    state: "{{ firewalld_package }}"
  become: true

- name: firewalld enabled
  service: 
    name: firewalld
    state: "{{ firewalld_state }}"
    enabled: "{{ firewalld_enabled }}"
  become: true

- name: permit traffic
  firewalld:
    port: "{{ vsftpd_ports }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  become: true
  notify: restart firewalld

- name: permit traffic passive connections
  firewalld:
    port: "{{ pasv_min_port }}-{{ pasv_max_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  become: true
  notify: restart firewalld
